from __future__ import annotations

ARK_MATCH_STATUS_SCHEDULED = "Scheduled"
ARK_MATCH_STATUS_LOCKED = "Locked"
ARK_MATCH_STATUS_CANCELLED = "Cancelled"
ARK_MATCH_STATUS_COMPLETED = "Completed"

ARK_MATCH_STATUSES_OPEN = {ARK_MATCH_STATUS_SCHEDULED, ARK_MATCH_STATUS_LOCKED}
